server:
  port: 0
spring:
  application:
    name: book-import
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"