logging:
  level:
    "[org.springframework]": debug
    "[root]": INFO
    "[com.luanvv.microservices]": DEBUG
spring:
  application:
    name: book-store
  devtools:
    livereload:
      enabled: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
---
spring:
  profiles: dev
  devtools:
    livereload:
      enabled: true