version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: bookstore_mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: bookRoot
      MYSQL_DATABASE: bookstore
      MYSQL_USER: book
      MYSQL_PASSWORD: book
  configuration-server:
    image: configuration-server:${VERSION}
    container_name: bookstore_configuration_server
    environment: 
      EUREKA_URI: "http://discovery-server:8761/eureka/"
    ports:
    - 8081:8081
    depends_on:
    - discovery-server
  discovery-server:
    image: discovery-server:${VERSION}
    container_name: bookstore_discovery_server
    restart: always
    ports:
    - 8761:8761
  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
  zookeeper:
    image: zookeeper:3.5.9
    hostname: zoo
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_DELETE_TOPIC_ENABL!E: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "10021:8080"
    restart: always
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:19092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
volumes:
  db_data: {}