version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: bookstore-mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - ${DATABASE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
volumes:
  db_data: {}