server:
  port: 8081

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          url: file:///${user.home}/application-config

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8082/eureka/

security:
  user:
    name: configUser
    password: configPassword
    role: SYSTEM
