server:
  port: 8081

spring:
  application:
    name: config
  security:
    user:
      name: configUser
      password: configPassword
      roles: SYSTEM
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luanvuhlu/bookstore-microservices
          searchPaths: application-config
      label: config
