server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
spring:
  application:
    name: config
  security:
    user:
      name: configUser
      password: configPassword
      roles: SYSTEM
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luanvuhlu/bookstore-config
      label: config
  zipkin:
    baseUrl: ${ZIPKIN_URL:localhost:9411}