# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-api:
    working_directory: ~/repo
    machine:
      image: ubuntu-2004:current
    environment:
      BASE_DIR: ./openapi
      MVN_SETTINGS: ./scripts/settings.xml
    steps:
#    - setup_remote_docker:
#        docker_layer_caching: true
    - checkout
    - restore_cache:
        keys:
          - v1-pip-dependencies-{{ .Branch }}-{{ checksum "openapi/scripts/requirements.txt" }}
          - v1-pip-dependencies-
    - run:
        name: "Install dependencies"
        command: |
          cd ${BASE_DIR}
          python3 -m venv venv
          . venv/bin/activate
          if [ -f scripts/requirements.txt ]; then 
            pip install -r scripts/requirements.txt; 
          fi
    - run:
        name: "Build"
        command: |
          cd ${BASE_DIR}
          . venv/bin/activate
          python scripts/deploy.py
    - run:
        name: "Publish to Github Packages"
        command: |
          for i in out/*/pom.xml;do 
            mvn --batch-mode deploy -s ${MVN_SETTINGS} -f "$i" -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/luanvuhlu/bookstore-openapi ; 
          done
    - save_cache: # ** special step to save dependency cache **
        key: v1-pip-dependencies-{{ .Branch }}-{{ checksum "openapi/scripts/requirements.txt" }}
        paths:
          - "venv"
  test:
    working_directory: ~/repo
    docker:
    - image: cimg/openjdk:11.0.12
    environment:
      MVN_SETTINGS: ./scripts/settings.xml
    steps:
#    - setup_remote_docker:
#        docker_layer_caching: true
    - checkout
    - restore_cache:
        keys:
          - v1-maven-dependencies-{{ checksum "pom.xml" }}
          - v1-maven-dependencies-
    - run:
        name: "Test Audit service"
        command: mvn -s ${MVN_SETTINGS} -B test --file audit/pom.xml
    - run:
        name: "Test Configuration service"
        command: mvn -s ${MVN_SETTINGS} -B test --file configuration-server/pom.xml
    - run:
        name: "Test Discovery service"
        command: mvn -s ${MVN_SETTINGS} -B test --file discovery-server/pom.xml
    - run:
        name: "Test Gateway service"
        command: mvn -s ${MVN_SETTINGS} -B test --file gateway/pom.xml
    - run:
        name: "Test Store service"
        command: mvn -s ${MVN_SETTINGS} -B test --file louis-store/pom.xml
    - run:
        name: "Test Order service"
        command: mvn -s ${MVN_SETTINGS} -B test --file order-service/pom.xml
    - run:
        name: "Test Product service"
        command: mvn -s ${MVN_SETTINGS} -B test --file product-service/pom.xml
    - save_cache:
        paths:
          - ~/.m2
        key: v1-maven-dependencies-{{ checksum "pom.xml" }}

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-then-push:
    jobs:
#      - build-api:
#          context: github-package-context
      - test:
          context: github-package-context
#          requires:
#            - build-api
