server:
  port: 0
eureka:
#  instance:
#    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      enabled: true

logging:
  level:
    org.springframework: debug
    root: INFO

spring:
  application:
    name: book-store
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        order_updates: true
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  devtools:
    livereload:
      enabled: true