server:
  port: 0
eureka:
#  instance:
#    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    "[org.springframework]": debug
    "[root]": INFO

spring:
  application:
    name: book-store
  cloud:
    function:
      definition: booksSender
    stream:
      bindings:
        booksSender-out-0:
          destination: book-import
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
#      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        order_updates: true
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:13306/bookstore?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: book
    password: book
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB