server:
  port: 9080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: bookStoreModule
        uri: lb://book-store
        predicates:
        - Path=/book-store/**
        filters:
        - RewritePath=/book-store/(?<segment>.*), /$\{segment}
        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"