# Generated by Django 4.1 on 2022-08-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0002_book_created_at_book_created_by_book_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
    ]
