# Generated by Django 4.1 on 2022-08-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0003_book_isbn_10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(max_length=10, unique=True, verbose_name='ISBN-10'),
        ),
    ]
