version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: bookstore_mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: bookRoot
      MYSQL_DATABASE: bookstore
      MYSQL_USER: book
      MYSQL_PASSWORD: book
  configuration-server:
    image: configuration-server:${VERSION}
    container_name: bookstore_configuration_server
    environment: 
      EUREKA_URI: "http://discovery-server:8761/eureka/"
    ports:
    - 8081:8081
    depends_on:
    - discovery-server
  discovery-server:
    image: discovery-server:${VERSION}
    container_name: bookstore_discovery_server
    restart: always
    ports:
    - 8761:8761
  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  kafka:
    image: wurstmeister/kafka
    container_name: book_import_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
volumes:
  db_data: {}