apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: bookRoot
            - name: MYSQL_DATABASE
              value: BOOKSTORE
            - name: MYSQL_USER
              value: book
            - name: MYSQL_PASSWORD
              value: book
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  type: NodePort
  selector:
    name: mysql
  ports:
    - port: 3306
      targetPort: 3306