server:
  port: 0
  
logging:
  level:
    "[root]": INFO
    "[org.springframework.jdbc.core]": TRACE
    
spring:
  application:
    name: book-import
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    function:
      definition: booksImport
    stream:
      bindings:
        booksImport-in-0:
          destination: book-import
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        order_updates: true
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:13306/bookstore?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: book
    password: book
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
