server:
  port: 8082

spring:
  application:
    name: discovery
#  cloud:
#    config:
#      enabled: false
eureka:
  instance:
   hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
