apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zipkin
  template:
    metadata:
      labels:
        name: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: default
spec:
  type: NodePort
  selector:
    name: zipkin
  ports:
    - port: 9411
      targetPort: 9411