--liquibase formatted sql
--changeset liquibase:0001.create_audit
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'AUDIT_MESSAGE' LIMIT 1;
CREATE TABLE IF NOT EXISTS AUDIT_MESSAGE(
	ID CHAR(36) NOT NULL,
	SERVICE_NAME VARCHAR(100) DEFAULT NULL,
	EVENT_ACTION VARCHAR(100) DEFAULT NULL,
	PRIVILEGE VARCHAR(100) DEFAULT NULL,
	USER_ID VARCHAR(100) DEFAULT NULL,
	DESCRIPTION VARCHAR(500) DEFAULT NULL,
	CREATED_DATE TIMESTAMP,
	PRIMARY KEY(ID));