CREATE TABLE book(
	id INT NOT NULL AUTO_INCREMENT, 
	title VARCHAR(100) NOT NULL, 
	author VARCHAR(100) DEFAULT NULL, 
	genre VARCHAR(50) DEFAULT NULL, 
	height INT NOT NULL, 
	publisher VARCHAR(100) DEFAULT NULL,
	PRIMARY KEY(id));